// <auto-generated />
using DSW1_T1_SALAS_JEREMY.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DSW1_T1_SALAS_JEREMY.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DSW1_T1_SALAS_JEREMY.Models.Curso", b =>
                {
                    b.Property<int>("CursoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CursoId"));

                    b.Property<string>("CodigoCurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Creditos")
                        .HasColumnType("int");

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<int>("NivelAcademicoId")
                        .HasColumnType("int");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CursoId");

                    b.HasIndex("NivelAcademicoId");

                    b.ToTable("Cursos");
                });

            modelBuilder.Entity("DSW1_T1_SALAS_JEREMY.Models.NivelAcademico", b =>
                {
                    b.Property<int>("NivelAcademicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NivelAcademicoId"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Orden")
                        .HasColumnType("int");

                    b.HasKey("NivelAcademicoId");

                    b.ToTable("NivelesAcademicos");
                });

            modelBuilder.Entity("DSW1_T1_SALAS_JEREMY.Models.Curso", b =>
                {
                    b.HasOne("DSW1_T1_SALAS_JEREMY.Models.NivelAcademico", "NivelAcademico")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelAcademicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelAcademico");
                });

            modelBuilder.Entity("DSW1_T1_SALAS_JEREMY.Models.NivelAcademico", b =>
                {
                    b.Navigation("Cursos");
                });
#pragma warning restore 612, 618
        }
    }
}
